name: Check Keystore

on:
  workflow_dispatch:

jobs:
  check_keystore:
    runs-on: ubuntu-latest

    steps:
      - name: 代码迁出 (Checkout)
        uses: actions/checkout@v4

      - name: 构建Java环境 (Setup Java)
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: 解码生成 jks
        run: echo "$KEYSTORE_BASE64" | base64 -di > app/keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: 检查 keystore.jks 文件是否存在
        run: |
          if [ -f app/keystore.jks ]; then
            echo "keystore.jks 文件存在。"
          else
            echo "keystore.jks 文件不存在。"
            exit 1
          fi

      - name: 检查 keystore.jks 文件大小
        run: ls -l app/keystore.jks

      - name: 检查 keystore.jks 文件内容 (前 10 行)
        run: head -n 10 app/keystore.jks

      - name: 验证 keystore.jks
        run: keytool -list -v -keystore app/keystore.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }}

      - name: 验证 GitHub Actions 解码。
        run: cat app/keystore.jks | base64 | diff - <(echo "${{ secrets.KEYSTORE_BASE64 }}")
